language: python
python: 
  - "3.6"

sudo: false

cache:
  directories:
      - "~/.platformio"

install:
  - pip install -U platformio
  - platformio lib install
  - platformio update

script:
  - platformio test -v -e native-test
  - platformio run --environment megaatmega2560