language: python
python: 
  - "3.6"

sudo: false

cache:
  directories:
      - "~/.platformio"

install:
  - pip install -U platformio
  - platformio update

script:
  - platformio test -v -e native-test